allowUnusedPatches: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - dprint
  - esbuild
  - sharp
  - spawn-sync

patchedDependencies:
  "@wxt-dev/analytics": patches/@wxt-dev__analytics.patch
